project:
  type: website
  output-dir: docs

website:
  title: "Exploits watershed predictions"
  navbar:
    left:
      - text: "Home" 
        href: index.qmd
      - text: "Sliders"
        href: Sliders.qmd
      - text: "Map"
        href: Exploits_map.qmd 

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false


